/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class VistaAFNDMostrarResultadosPanel extends javax.swing.JPanel {

    /**
     * Creates new form VistaAFDMostrarDatosPanel
     */
    public VistaAFNDMostrarResultadosPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        lblEstados = new javax.swing.JLabel();
        lblInicial = new javax.swing.JLabel();
        lblFinales = new javax.swing.JLabel();
        lblTransiciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtATransiciones = new javax.swing.JTextArea();
        lblResultado = new javax.swing.JLabel();
        lblResultadoValor = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        lblTipoValor = new javax.swing.JLabel();
        lblEstadosValor = new javax.swing.JLabel();
        lblInicialValor = new javax.swing.JLabel();
        lblFinalesValor = new javax.swing.JLabel();
        lblTransicionesLambda = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtATransicionesLambda = new javax.swing.JTextArea();
        btnMostarGrafica = new javax.swing.JButton();

        lblTipo.setText("TIPO:");

        lblEstados.setText("ESTADOS:");

        lblInicial.setText("INICIAL:");

        lblFinales.setText("FINALES:");

        lblTransiciones.setText("TRANSICIONES");

        txtATransiciones.setColumns(20);
        txtATransiciones.setRows(5);
        jScrollPane1.setViewportView(txtATransiciones);

        lblResultado.setText("RESULTADO:");

        btnAceptar.setText("Aceptar");
        btnAceptar.setActionCommand("AceptarMRP");

        lblTipoValor.setText("jLabel1");

        lblEstadosValor.setText("jLabel2");

        lblInicialValor.setText("jLabel3");

        lblFinalesValor.setText("jLabel4");

        lblTransicionesLambda.setText("TRANSICIONES LAMBDA");

        txtATransicionesLambda.setColumns(20);
        txtATransicionesLambda.setRows(5);
        jScrollPane2.setViewportView(txtATransicionesLambda);

        btnMostarGrafica.setText("Mostrar Grafica");
        btnMostarGrafica.setActionCommand("MostrarGrafica");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblEstados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstadosValor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 216, Short.MAX_VALUE)
                        .addComponent(lblResultado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultadoValor)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTipoValor))
                            .addComponent(lblTransiciones)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblInicial)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInicialValor))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblFinales)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblFinalesValor)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTransicionesLambda)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMostarGrafica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAceptar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(lblTipoValor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstados)
                    .addComponent(lblResultado)
                    .addComponent(lblResultadoValor)
                    .addComponent(lblEstadosValor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInicial)
                    .addComponent(lblInicialValor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinales)
                    .addComponent(lblFinalesValor))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTransiciones)
                    .addComponent(lblTransicionesLambda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAceptar)
                            .addComponent(btnMostarGrafica))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnAceptar;
    public javax.swing.JButton btnMostarGrafica;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JLabel lblEstados;
    public javax.swing.JLabel lblEstadosValor;
    public javax.swing.JLabel lblFinales;
    public javax.swing.JLabel lblFinalesValor;
    public javax.swing.JLabel lblInicial;
    public javax.swing.JLabel lblInicialValor;
    public javax.swing.JLabel lblResultado;
    public javax.swing.JLabel lblResultadoValor;
    public javax.swing.JLabel lblTipo;
    public javax.swing.JLabel lblTipoValor;
    public javax.swing.JLabel lblTransiciones;
    public javax.swing.JLabel lblTransicionesLambda;
    public javax.swing.JTextArea txtATransiciones;
    public javax.swing.JTextArea txtATransicionesLambda;
    // End of variables declaration//GEN-END:variables
}
